name: Android Build

on:
  push:
    branches: [main]    # ya koi feature branch
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK (Java 17 recommended for recent Gradle/Android)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Cache Gradle dependencies to speed up builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 4. Run Gradle build
      - name: Build APK
        run: ./gradlew assembleDebug  # or assembleRelease if signing ready

      # 5. Upload APK as artifact for download
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
