name: Extract Server ZIP

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: 'Name for the extracted folder'
        required: false
        default: 'extracted-server'
        type: string

jobs:
  extract-server:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if server.zip exists
        run: |
          if [ ! -f "server.zip" ]; then
            echo "Error: server.zip not found in repository"
            exit 1
          fi
          echo "Found server.zip ($(du -h server.zip | cut -f1))"
          
      - name: Create target directory
        run: |
          TARGET_DIR="${{ github.event.inputs.target_folder || 'extracted-server' }}"
          echo "Creating directory: $TARGET_DIR"
          mkdir -p "$TARGET_DIR"
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV
          
      - name: Extract server.zip
        run: |
          echo "Extracting server.zip to $TARGET_DIR..."
          unzip -q server.zip -d "$TARGET_DIR/"
          echo "Extraction completed successfully"
          
      - name: List extracted contents
        run: |
          echo "Contents extracted to $TARGET_DIR:"
          ls -la "$TARGET_DIR/"
          echo "Total size:"
          du -sh "$TARGET_DIR/"
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit extracted files
        run: |
          git add "$TARGET_DIR/"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Extract server.zip contents to $TARGET_DIR

            - Extracted server.zip archive
            - Created new folder: $TARGET_DIR
            - Auto-generated by GitHub Actions workflow"
            echo "Changes committed successfully"
          fi
          
      - name: Push changes
        run: |
          git push origin main
          echo "Changes pushed to repository"
          
      - name: Summary
        run: |
          echo "🎉 Server extraction completed successfully!"
          echo "📁 Extracted to: $TARGET_DIR"
          echo "📊 Check the repository for the new folder with extracted contents"