name: Build ChessBotApp APK

on:
  push:
    branches:
      - main  # ya tumhare branch ka naam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up JDK 11 (AGP 8.x + Kotlin 1.9 requirement)
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3. Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 4. Build Debug APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    # 5. Upload APK as artifact
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: ChessBotApp-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk          sudo apt-get update
          sudo apt-get install -y gradle
          gradle assembleDebug --stacktrace
        fi

    # 5. Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ChessBotApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
