name: Build ChessBotApp APK

on:
  push:
    branches:
      - main  # ya tumhare branch ka naam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Set up JDK 11
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3. Make gradlew executable if exists
    - name: Make gradlew executable
      run: |
        if [ -f ./gradlew ]; then
          chmod +x ./gradlew
        fi

    # 4. Build APK using gradlew if exists, else use system Gradle
    - name: Build Debug APK
      run: |
        if [ -f ./gradlew ]; then
          ./gradlew assembleDebug --stacktrace
        else
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle assembleDebug --stacktrace
        fi

    # 5. Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ChessBotApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
